config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]

get 'signup', to: 'users#new'
resources :users, except: [:new]

get 'login', to: 'sessions#new'
post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  # validations for article
  belongs_to :user
validates :title, presence: true, length: {minimum: 6, maximum: 100}
validates :description, presence: true, length: {minimum: 10, maximum: 300}
validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  before_save {self.email = email.downcase}
# getting validations for user
validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimun: 3, maximum: 25}

# getting validations for email
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }

has_secure_password
def self.search(param)
  param.strip!
  to_send_back = username_matches(param) + email_matches(param).uniq
  return nil unless to_send_back
  to_send_back 
end

def self.username_matches(param)
matches('username', param)
end

def self.email_matches(param)
matches('email', param)
end

def self.matches(field_name, param)
  where("#{field_name} like ?", "%#{param}%")
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
    helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  
  end

  def logged_in?
    !!current_user
    end

  def require_user
      if !logged_in?
    flash[:danger] = "You must be logged in to perform that action"
    redirect_to root_path

  end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

def show
  @article = Article.find(params[:id])      #finds article
end

  def index
      @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def edit
    @article = Article.find(params[:id])
  end

    def create
      @article = Article.new(params.require(:article).permit(:title, :description))
      @article.user = User.first
# if the query is saved then display flash message
      if @article.save
        flash[:success] = "Query was successfully created."
        redirect_to @article
      else
        render 'new'
      end

    end

    def update
      @article = Article.find(params[:id])
      if @article.update(params.require(:article).permit(:title, :description))
        flash[:success] = "Query was updated successfully."
        redirect_to @article
      else
        render 'edit'
      end
    end

def destroy
  @article = Article.find(params[:id])
  @article.destroy
  flash[:danger] = "Query was deleted."
  redirect_to articles_path
end

end

app/controllers/channels/application_cable/channel.rb
module ApplicationCable
  class Channel < ActionCable::Channel::Base
  end
end

app/controllers/channels/application_cable/connection.rb
module ApplicationCable
  class Connection < ActionCable::Connection::Base
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new

  end
# checks to see if the users login details are correct:
# if so they get redirectd to their account and if not they get an error message
def create
  user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
          flash[:success] = "You have successfully logged in"
            redirect_to user_path(user)

          else

    flash.now[:danger] = "There was something wrong with your login information"
    render 'new'
end
  end

def destroy
  session[:user_id] = nil
  flash[:success] = "You have logged out"
  redirect_to root_path
  end
    end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]

def index
  @users = User.all
end


def new
  @user = User.new
  end

# signup page
  def create
      @user = User.new(user_params)
        if @user.save
# flash message welcoming the user when they create an account
            flash[:success] = "Welcome to our Work Shop #{@user.username}"
              redirect_to articles_path
            else
              render 'new'
            end
          end



        def edit
          end

          def show

              end


          def update
              if @user.update(user_params)
                flash[:success] = "Your account was updated successfully"
                redirect_to articles_path

                  else
                    render 'edit'
                  end
                end

                private
                def user_params
                  params.require(:user).permit(:username, :email, :password)
                end
              end

def set_user
  @user = User.find(params[:id])
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
          image_tag(gravatar_url, alt: user.username, class: "img-circle")
end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>

  <div class="row">
    <div class="col-8 offset-2">
      <div class="cards card-body bg-dark" >

        <div class="article-title">

          <%= link_to article.title, article_path(article) %>

        </div>
        <!-- adds user data to records -->
        <div class="article-body">
          <%= truncate(article.description, length: 100, ) %>
          <div class="article-meta-details">

          <small>Created by: <%= article.user.username if article.user%>,
          <%= time_ago_in_words(article.created_at) %> ago, last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>

          </div>

        </div>
        <div class="article-actions">
          <%= link_to "Edit this query", edit_article_path(article), class: "btn btn-xs btn-primary" %>
</div>

<div class="article-delete">
  <div class="col-8 offset-9">
  <%= button_to "Delete this query", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this query?"}, class: "btn btn-xs btn-danger" %>
</div>
</div>


      </div>
    </div>
</div>

<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class = 'row'>
  <div class = 'col-12'>
      <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class = "form-group">
        <div class = "control-label col-2">

          <%= f.label :title %>
      </div>
      <div class = 'col-11'>
          <%= f.text_field :title, class: "form-control",placeholder: "Title of Query",autofocus:true %>

    </div>
    </div>
    <div class = "form-group">
      <div class = "control-label col-2">

          <%= f.label :description %>
          </div>
            <div class = 'col-11'>
          <%= f.text_area :description, rows: 10, class: "form-control",placeholder: "Body of Query"%>
        </div>

        <div class = "form-group">
          <div class = "col-4">
          <%= f.submit class: "btn btn-primary btn-md" %>
          </div>
          </div>
      <% end %>

      <div class ="col-4 offset-4">

    </div>
</div>
</div>

app/views/articles/edit.html.erb
<h1 align = center>Edit article</h1>

<%= render 'form' %>

[<%= link_to 'Cancel and Return', articles_path %>]

app/views/articles/index.html.erb
<h1 align = "center"> Query listing page</h1>

<%= render 'article', obj: @articles %>

app/views/articles/new.html.erb
<h1 align = "center"> Create a new Query</h1>

<%= render 'form' %>

app/views/articles/search.html.erb
<% obj.each do |article| %>

  <div class="row">
    <div class="col-8 offset-2">
      <div class="cards card-body bg-dark" >

        <div class="article-title">

          <%= link_to article.title, article_path(article) %>

        </div>
        <!-- adds user data to records -->
        <div class="article-body">
          <%= truncate(article.description, length: 100, ) %>
          <div class="article-meta-details">

          <small>Created by: <%= article.user.username if article.user%>,
          <%= time_ago_in_words(article.created_at) %> ago, last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>

          </div>

        </div>
        <div class="article-actions">
          <%= link_to "Edit this query", edit_article_path(article), class: "btn btn-xs btn-primary" %>
</div>

<div class="article-delete">
  <div class="col-8 offset-9">
  <%= button_to "Delete this query", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this query?"}, class: "btn btn-xs btn-danger" %>
</div>
</div>


      </div>
    </div>
</div>

<% end %>

app/views/articles/show.html.erb
<h2 align = "center"> Title:  <%= @article.title %> </h2>

<div class="col-8 offset-2">
<div class="cardss card-body" >
  <ul class="listing">

    <div class="row">

      <div class="cardz col-4 offset-5">
<li>Created by:</li>
        <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>

        <li class="article-title">
<!-- goes to users page -->
          <%= link_to @article.user.username, user_path(@article.user) %>


        </li>
<!-- shows if the user has any records  -->
        <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
      </div>

    </div>
  </ul>
  <h4 class ="center"><strong>Description:</strong></h4>
  <hr>
    <%= simple_format(@article.description) %>
    <div class="articles-actions">

<%= link_to 'Edit', edit_article_path(@article), class: "btn btn-xs btn-primary" %>

<%= link_to 'View all Queries', articles_path, class: "btn btn-xs btn-success" %>

</div>
</div>

app/views/layouts/_messages.html.erb
<div class="row">

  <div class="col-10 offset-1">
    <% flash.each do |name, msg| %>
    <div class='alert alert-<%="#{name}" %>'>
      <a href="#" class="close" data-dismiss="alert">×</a>
<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
<% end %>
</div>
</div>

app/views/layouts/_navigation.html.erb
<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <%= link_to "Work Shop", root_path, class:"navbar-brand", id: "logo"%>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <% if logged_in? %>
      <li class="nav-item active">


      </li>

      <li class="nav-item">
        <a class="nav-link" <%= link_to "Queries", articles_path %></a>
      </li>
      <li>
         <a class="nav-link" <%= link_to "New Query", new_article_path %></a>
      </li>

      <li>
         <a class="nav-link" <%= link_to "Login", login_path %></a>
      </li>
      <li>
         <a class="nav-link" <%= link_to "Edit User", edit_user_path(current_user) %></a>
      </li>
      <li>
         <a class="nav-link" <%= link_to "View your profile", user_path(current_user) %></a>
      </li>

      <li>
         <a class="nav-link" <%= link_to "View all users", users_path %></a>
      </li>

      <form class="form-inline">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>


    </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Work Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>


    <div class = "container">
    <%= render 'layouts/navigation' %>
    <% flash.each do |name, msg| %>
      <%= msg %>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">

  <h1 class="display-4">Welcome!</h1>
  <p class="lead">This web application allows you to create a query for our mechanics to look at. They will then get back to you with a price.</p>
  <hr class="my-4">
  <p>Click the "Create Account" button to get started!.</p>
  <a class="btn btn-primary btn-lg" <%= link_to 'Create an Account', signup_path %></a>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<!-- add a panel/card that displays an error if the credentials aren't met -->
<div class="row">
  <div class ="col-8 offset-2">
    <div class ="card bg-danger">
      <div class="card-body">
      <div class = "card-heading">
        <h2 class = "card-title">
          <%= pluralize(obj.errors.count, "error")%>
          prohibit this query from being saved:
          </h2>

          <div class = "card-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          </div>
        </div>
        </div>
      </div>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class = 'row'>
  <div class = 'col-12'>
      <%=form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class = "form-group">
        <div class = "control-label col-2">

          <%= f.label :username %>
      </div>
      <div class = 'col-11'>
          <%= f.text_field :username, class: "form-control",placeholder: "Enter username",autofocus:true %>

    </div>
    </div>
    <div class = "form-group">
      <div class = "control-label col-2">

          <%= f.label :email %>
          </div>
            <div class = 'col-11'>
          <%= f.email_field :email, class: "form-control",placeholder: "Enter email"%>
        </div>

        <div class = "form-group">
          <div class = "control-label col-2">

              <%= f.label :password %>
              </div>
                <div class = 'col-11'>
              <%= f.password_field :password, class: "form-control",placeholder: "Enter password"%>
            </div>

        <div class = "form-group">
          <div class = "col-10">
          <%= f.submit(@user.new_record? ? "Sign up" : "update account", class: "btn btn-primary btn-md") %>
          </div>
          </div>
      <% end %>

      <div class ="col-4 offset-4">

    </div>
</div>
</div>

app/views/users/edit.html.erb
<h1 align = "center"> Edit account </h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Users</h1>
<!-- shows all users -->

  <div align="center">
    <% @users.each do |user| %>

      <ul class="listing">

        <div class="row">

          <div class="cardz col-4 offset-4">

            <li><%= link_to gravatar_for(user), user_path(user) %></li>

            <li class="article-title">
  <!-- goes to users page -->
              <%= link_to user.username, user_path(user) %>


            </li>
<!-- shows if the user has any records  -->
            <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
          </div>

        </div>
      </ul>
      <% end %>
    </div>

app/views/users/new.html.erb
<h1 align = "center"> Sign Up </h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align = "center"> Welcome to <%= @user.username %>'s page </h1>

<div class = "row">
  <div class="col-4 offset-4 center">
    <%= gravatar_for @user, size:150 %>
  </div>
  </div>

<h4 align = "center"><%= @user.username %>'s articles </h4>
<%= render 'articles/article', obj: @user.articles %>